# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude: omrun/ui
    -   id: check-toml
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: local
    hooks:
    -   id: black
        name: Format python code by black
        entry: .venv/bin/black
        args:
        -   .
        language: system
        pass_filenames: false
    -   id: isort
        name: Format python code by isort
        entry: .venv/bin/isort
        args:
        -   .
        language: system
        pass_filenames: false
    -   id: pflake8
        name: Check python code by pflake8
        entry: .venv/bin/pflake8
        language: system
        pass_filenames: false
    -   id: uic-mainwindow
        name: Generate code by uic
        entry: .venv/bin/pyside6-uic
        args:
        -   -o
        -   omrun/ui/mainwindow.py
        language: system
        files: ui/mainwindow.ui
    -   id: uic-modelbrowser
        name: Generate code by uic
        entry: .venv/bin/pyside6-uic
        args:
        -   -o
        -   omrun/ui/modelbrowser.py
        language: system
        files: ui/modelbrowser.ui
    -   id: uic-setupdialog
        name: Generate code by uic
        entry: .venv/bin/pyside6-uic
        args:
        -   -o
        -   omrun/ui/setupdialog.py
        language: system
        files: ui/setupdialog.ui
